name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # suficiente para públicos
          user: arpedeveloper
          template: classic
          base: header
          config_timezone: America/Merida

          # Plugins que sustituyen “trofeos”
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 6

          # Opcionales (puedes quitar)
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Salida
          filename: assets/metrics.svg
